# Generated by Django 4.0.3 on 2022-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('favoriteAnimal', models.CharField(default='', max_length=50)),
                ('favoriteColor', models.CharField(default='', max_length=50)),
                ('animal', models.ManyToManyField(blank=True, related_name='aminals', to='animals.animal')),
            ],
        ),
    ]
